export const tags = {
  "Information Technology": [
    "Front end development",
    "Back end development",
    "Cloud computing",
    "AI/ML",
    "Data Science",
    "Cybersecurity",
    "DevOps",
    "Software development",
  ],
  "Design (UI/UX)": [
    "User research",
    "Content strategy",
    "Information Architecture (UX)",
    "Visual design (UI)",
    "UI/UX development",
    "Product designer",
  ],
  Analytics: [
    "Hacking Skills",
    "Math and statistics knowledge",
    "Traditional Research",
    "Machine learning",
  ],
  Product: ["UX", "Business", "Tech"],
  Core: ["Mechanical", "Chemical", "Civil"],
  Phoenix: [
    "Microelectronics",
    "Communications",
    "Instrumentation",
    "Power generation and transmission",
  ],
  Finance: [
    "Investment Banking",
    "Corporate Finance",
    "Business Validation",
    "Business Validation",
    "Portfolio Management",
    "Financial Planning",
    "Financial Modelling",
    "Risk Management",
    "Actuary",
  ],
};
